#
# Makefile for the hideep drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_HIDEEP_BLUEBERRY) += hideep.o
hideep-objs := hideep_ts.o hideep_fw.o hideep_iface.o hideep_sysfs.o hideep_Testmode.o hideep_update_i2c.o hideep_rawdata.o
